import { Pool } from "pg";
import { z } from "zod";
import { listSeedTransactions } from "./finance-store";
import {
  listStoredPortfolioInstallments,
  listStoredPortfolioLoanSimulations,
  listStoredPortfolioLoans,
} from "./portfolio-store";

const databaseEnvSchema = z.object({
  DATABASE_URL: z.string().trim().min(1).default("postgresql://postgres:postgres@localhost:5432/credix_v2"),
});

const databaseEnv = databaseEnvSchema.parse(process.env);

let pool: Pool | null = null;

function getPool() {
  if (!pool) {
    pool = new Pool({
      connectionString: databaseEnv.DATABASE_URL,
    });
  }

  return pool;
}

async function ensureFinanceTables() {
  const db = getPool();

  await db.query(`
    CREATE TABLE IF NOT EXISTS finance_transactions (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
      amount NUMERIC(14, 2) NOT NULL CHECK (amount > 0),
      category VARCHAR(120) NOT NULL,
      "date" VARCHAR(10) NOT NULL,
      description VARCHAR(300) NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('completed', 'scheduled', 'pending')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await db.query(`
    CREATE INDEX IF NOT EXISTS finance_transactions_date_idx
      ON finance_transactions ("date" DESC, id DESC)
  `);
}

async function seedFinanceTransactions() {
  const db = getPool();
  const result = await db.query<{ count: string }>("SELECT COUNT(*)::text AS count FROM finance_transactions");
  const total = Number(result.rows[0]?.count || "0");

  if (total > 0) {
    return;
  }

  const seedRows = listSeedTransactions();
  for (const item of seedRows) {
    await db.query(
      `
        INSERT INTO finance_transactions (id, type, amount, category, "date", description, status)
        VALUES ($1, $2, $3, $4, $5, $6, $7)
      `,
      [
        Number(item.id),
        item.type,
        item.amount,
        item.category,
        item.date,
        item.description,
        item.status,
      ],
    );
  }

  await db.query(`
    SELECT setval(
      pg_get_serial_sequence('finance_transactions', 'id'),
      COALESCE((SELECT MAX(id) FROM finance_transactions), 1),
      true
    )
  `);
}

async function ensurePortfolioTables() {
  const db = getPool();

  await db.query(`
    CREATE TABLE IF NOT EXISTS portfolio_loans (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      customer_name VARCHAR(180) NOT NULL,
      principal_amount NUMERIC(14, 2) NOT NULL CHECK (principal_amount > 0),
      issued_at VARCHAR(10) NOT NULL,
      first_due_date VARCHAR(10) NOT NULL,
      interest_type TEXT NOT NULL CHECK (interest_type IN ('simples', 'composto', 'fixo')),
      interest_rate NUMERIC(10, 4) NOT NULL DEFAULT 0,
      fixed_fee_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
      observations TEXT NOT NULL DEFAULT '',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS portfolio_installments (
      id VARCHAR(40) PRIMARY KEY,
      loan_id BIGINT NOT NULL REFERENCES portfolio_loans(id) ON DELETE CASCADE,
      customer_name VARCHAR(180) NOT NULL,
      installment_number INT NOT NULL,
      total_installments INT NOT NULL,
      due_date VARCHAR(10) NOT NULL,
      paid_date VARCHAR(10),
      principal_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
      interest_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
      amount NUMERIC(14, 2) NOT NULL CHECK (amount >= 0),
      status TEXT NOT NULL CHECK (status IN ('pending', 'completed')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await db.query(`
    CREATE INDEX IF NOT EXISTS portfolio_installments_loan_idx
      ON portfolio_installments (loan_id, installment_number)
  `);

  await db.query(`
    CREATE INDEX IF NOT EXISTS portfolio_installments_due_idx
      ON portfolio_installments (due_date, status)
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS portfolio_loan_simulations (
      id VARCHAR(40) PRIMARY KEY,
      customer_name VARCHAR(180) NOT NULL,
      principal_amount NUMERIC(14, 2) NOT NULL CHECK (principal_amount > 0),
      total_amount NUMERIC(14, 2) NOT NULL CHECK (total_amount >= principal_amount),
      installments_count INT NOT NULL,
      interest_type TEXT NOT NULL CHECK (interest_type IN ('simples', 'composto', 'fixo')),
      interest_rate NUMERIC(10, 4) NOT NULL DEFAULT 0,
      fixed_fee_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
      status TEXT NOT NULL CHECK (status IN ('DRAFT', 'SENT', 'ACCEPTED', 'EXPIRED', 'CANCELED')),
      expires_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
}

async function seedPortfolioData() {
  const db = getPool();
  const loanCountResult = await db.query<{ count: string }>("SELECT COUNT(*)::text AS count FROM portfolio_loans");
  const loanCount = Number(loanCountResult.rows[0]?.count || "0");

  if (loanCount === 0) {
    const loans = listStoredPortfolioLoans();
    for (const item of loans) {
      await db.query(
        `
          INSERT INTO portfolio_loans (
            id,
            customer_name,
            principal_amount,
            issued_at,
            first_due_date,
            interest_type,
            interest_rate,
            fixed_fee_amount,
            observations
          )
          VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        `,
        [
          Number(item.id),
          item.customerName,
          item.principalAmount,
          item.issuedAt,
          item.firstDueDate,
          item.interestType,
          item.interestRate,
          item.fixedFeeAmount,
          item.observations,
        ],
      );
    }

    await db.query(`
      SELECT setval(
        pg_get_serial_sequence('portfolio_loans', 'id'),
        COALESCE((SELECT MAX(id) FROM portfolio_loans), 1),
        true
      )
    `);
  }

  const installmentCountResult = await db.query<{ count: string }>("SELECT COUNT(*)::text AS count FROM portfolio_installments");
  const installmentCount = Number(installmentCountResult.rows[0]?.count || "0");
  if (installmentCount === 0) {
    const installments = listStoredPortfolioInstallments();
    for (const item of installments) {
      await db.query(
        `
          INSERT INTO portfolio_installments (
            id,
            loan_id,
            customer_name,
            installment_number,
            total_installments,
            due_date,
            paid_date,
            principal_amount,
            interest_amount,
            amount,
            status
          )
          VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
        `,
        [
          item.id,
          Number(item.loanId),
          item.customerName,
          item.installmentNumber,
          item.totalInstallments,
          item.dueDate,
          item.paidDate,
          item.principalAmount,
          item.interestAmount,
          item.amount,
          item.status,
        ],
      );
    }
  }

  const simulationCountResult = await db.query<{ count: string }>("SELECT COUNT(*)::text AS count FROM portfolio_loan_simulations");
  const simulationCount = Number(simulationCountResult.rows[0]?.count || "0");
  if (simulationCount === 0) {
    const simulations = listStoredPortfolioLoanSimulations();
    for (const item of simulations) {
      await db.query(
        `
          INSERT INTO portfolio_loan_simulations (
            id,
            customer_name,
            principal_amount,
            total_amount,
            installments_count,
            interest_type,
            interest_rate,
            fixed_fee_amount,
            status,
            expires_at
          )
          VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
        `,
        [
          item.id,
          item.customerName,
          item.principalAmount,
          item.totalAmount,
          item.installmentsCount,
          item.interestType,
          item.interestRate,
          item.fixedFeeAmount,
          item.status,
          item.expiresAt,
        ],
      );
    }
  }
}

export async function initializeDatabase() {
  await ensureFinanceTables();
  await ensurePortfolioTables();
  await seedFinanceTransactions();
  await seedPortfolioData();
}

export async function pingDatabase() {
  await getPool().query("SELECT 1");
}

export function getDatabasePool() {
  return getPool();
}
